### ISSUE TITLE
UI Feedback

### ISSUE THREAD

**Issue by PlayFabNoah** [PlayFab/UnityEditorExtensions#21] opened 2016-08-24 22:52 UTC
Overall functionality seems good, I mostly have a few gripes with the UI. In particular, the black background sticks out; gray would be preferable. I also can't tell if the font is the main Unity font, but it's also kind of hard to read (and a little bit fuzzy).

Other small issues:
- Why are there two game manager buttons, the "game manager" and the little box?
- The Studios menu is black text on a black background
- Should the secret key under titles show automatically? Maybe have some kind of spoiler tag, where you have to click it to show up
- Ticking the boxes on the "enable API" menu freezes it up for a few seconds and then changes which window is open.
- Not very clear that you have to hit "save" under the project to actually select it. A few things also act strangely if no project is currently selected, like the Data tab.
- Shouldn't API settings be per project? They aren't currently.

**Comment by zac-playfab** [comment] 2016-08-25 01:01
UI is staying for now, but I will A/B test various combinations. This was built on the pro skin, so admittedly it looks better on pro than on personal.

I am not too happy with the font either, this is a custom font, and I will revisit other fonts.

Other Issues:
1) Limitation of Unity's Editor UI. This was a direct copy with the Unity Services Tab. Also the icon provides the button functionality when the view with is very narrow.
2) Yep, just pushed a fix for this. (forgot about the personal GUI skin)
3) eh, you can collapse them and they are effectively hidden. These are developers so we are really not at risk of exposing this within the editor.
4) By design, checking that box adds compiler definitions that forces Unity to recompile
5) Yeah, I will look at making this better in the V1 release.
6) it is, it may not be very apparent in this editor. In this case Project means Unity Project, not PlayFab project.

**Closed by zac-playfab** 2016-08-25 01:01 UTC
