### ISSUE TITLE
"No SDK is installed" prompt in Unity 2018.1.0f2

### ISSUE THREAD

**Issue by christophe-h-mary** [PlayFab/UnityEditorExtensions#74] opened 2018-05-11 17:25 UTC
Since I updated to Unity 2018.1, I keep getting this prompt, even if the project has the sdk. Sometimes, it looses the project settings, and I have to re-enter them.
Usually when hitting play, the message changes to "you have the latest sdk".
Quite annoying...
<a href="https://ibb.co/jnn8yy"><img src="https://thumb.ibb.co/jnn8yy/playfab_unity_2018.jpg" alt="playfab_unity_2018" border="0"></a>

**Comment by Jelko123** [comment] 2018-05-27 04:46
Yeah same for me here really annoying issue!

**Comment by pgilmorepf** [comment] 2018-05-29 16:47
Thanks for reporting this.
I've seen it myself, and I should have been more diligent about addressing it.
I have found that if you click any source file and reload, the PlayFab Panel refreshes and the Panel understands that the SDK is installed again.
Also, restarting Unity entirely usually fixes it, though, I admit that sucks.

We have filed a bug internally, and will address this properly soon.
Leaving this issue open until we've addressed it.  Thanks!

**Comment by pgilmorepf** [comment] 2018-05-30 05:05
This change:
https://github.com/PlayFab/UnityEditorExtensions/pull/75
Should ensure that you're not _stuck_ in that state anymore, but unfortunately, I wasn't able to get to the bottom of it. There's some kind of timing issue with the Unity dll builder/loader, and there's a delay in when the SDK classes are available to the Editor panel via reflection. This effect is more pronounced in 2018 than it's ever been before, but I don't think it's entirely new.

At any rate, we'll keep investigating, but probably not on an urgent basis. I think you will be unblocked by today's changes, so take a look.

That commit came in AFTER today's publish, so unfortunately you'll have to use the following package from the automated branch for the next few weeks:
https://github.com/PlayFab/UnityEditorExtensions/blob/automated/Packages/PlayFabEditorExtensions.unitypackage

**Comment by bfops** [comment] 2018-06-10 21:10
I've been hitting this really frequently too. For me the problem is that it causes the playfab editor extension window to pop up overtop of some other useful window (since I don't otherwise devote screen real estate to the playfab editor extension window). If there were an option to disable that behavior then it wouldn't matter to me that something got briefly confused behind the scenes.

**Comment by pgilmorepf** [comment] 2018-06-21 18:34
I'm testing a new resolution to this issue.
Please give this a try:
https://github.com/PlayFab/UnityEditorExtensions/blob/pgilmore/EditorPrefsToSO/Packages/PlayFabEditorExtensions.unitypackage

It's a pre-release of a possible fix.
Please download package and install manually, and respond with any feedback.

**Comment by bfops** [comment] 2018-06-22 01:16
Downloaded & installed. In the ~5 minutes since I've reopened unity I haven't the issue repro so I'm hopeful! If I don't report back then it's safe to assume it's working as intended for our team!

**Comment by pgilmorepf** [comment] 2018-06-27 20:40
All indications are that this is now fixed in master. It's already in the asset package here:
https://github.com/PlayFab/UnityEditorExtensions/blob/master/Packages/PlayFabEditorExtensions.unitypackage
And will be in the versioned branch in the next release.

**Closed by pgilmorepf** 2018-06-27 20:40 UTC
