### ISSUE TITLE
Unity editor extensions focus

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnityEditorExtensions#63] opened 2017-03-09 08:45 UTC
forwarding issue posted on forum ICYMI:
PlayFab editor extension window is constantly grabbing focus - even from background.
Issue happens on Unity 5.3.3f1.
[link, report on Unity 5.5.2p4](https://community.playfab.com/questions/8859/unity-editor-extensions-focus.html)

**Comment by victor-kallai** [comment] 2017-03-09 09:03
This is a duplicate of the closed issue #61 
Solution: Comment or delete line 77 from PlayFabEditor.cs with the [InitializeOnLoad] attribute.

**Comment by pgilmorepf** [comment] 2017-03-09 23:03
We just fixed this issue... again.
It's on the latest master branch.

**Closed by pgilmorepf** 2017-03-09 23:03 UTC
